image: Visual Studio 2019

version: 2.0.0-alpha+{build}

environment:
  # DEBUG: w3c-xml-validator
  matrix:
    - node_version: '18'
    - node_version: '16'
    - node_version: '14'
    - node_version: '12'
    - node_version: '10'

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:node_version

before_test:
  - npm --version
  - npm install
  - npm install mocha-junit-reporter

test_script:
  - npm run lint
  - npx mocha --reporter mocha-junit-reporter index.spec.js test/functional/*
  - ps: |
        $webClient = New-Object System.Net.WebClient
        $webClient.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results.xml))

build: off
