git:
  quiet: true

os: linux
dist: focal

language: node_js

node_js:
  - "18"
  - "16"
  - "14"
  - "12"
  - "10"

env:
  global:
    - DEBUG=w3c-xml-validator

install:
  - npm install

script:
  - npm test

after_success:
  - npm run report-coverage
